-- Metadata of a service token. The signed token is never stored (ADR-006).
CREATE TABLE auth_schema.service_token (
  -- the jti, generated by the domain: no default, so a row cannot invent its own id
  token_id     uuid        NOT NULL,
  service      text        NOT NULL,
  permissions  text[]      NOT NULL,
  -- the ADMIN who requested the token; its foreign key is in V012
  issued_by    uuid        NOT NULL,
  issued_at    timestamptz NOT NULL DEFAULT now(),
  expires_at   timestamptz NOT NULL,
  CONSTRAINT pk_service_token PRIMARY KEY (token_id),
  CONSTRAINT chk_service_token_service CHECK (service IN ('synkro-workflow', 'synkro-worker')),
  CONSTRAINT chk_service_token_expiry CHECK (expires_at > issued_at)
);
